### ISSUE TITLE
Solve exercises of Hello, Python

### ISSUE THREAD

**Issue by karsterr** [karsterr/CSIT-Programming-with-Python#1]
Write the solutions of exercises

**Comment by angrezichatterbox** [comment]
For what should I write solutions for and how .. I would like to contribute

**Comment by karsterr** [comment]
> For what should I write solutions for and how .. I would like to contribute

I create this repo for studying my lesson. There is a pdf of the book that we use. I'll upload that pdf to the repo today. Also I appreciate your future contributions. 👍🏼

**Comment by karsterr** [comment]
@angrezichatterbox, I uploaded lesson document. Also I included example file design in .example file.

**Comment by Jainil2004** [comment]
hi @karsterr, I have looked at the uploaded lesson document and also understood how to contribute to this project. Can you please assign me this issue as i would love to contribute.
thank you

**Comment by Jainil2004** [comment]
@karsterr thank you for assigning the issue, i will update you as soon as i am done with the task.

**Comment by Jainil2004** [comment]
hi @karsterr, i have solved the mentioned issue. Please review the pull request and let me know if anything seems out of place or you would like to make some changes. I'll be happy to help resolve the issue.
thank you for providing me with this opportunity.

**Comment by karsterr** [comment]
@Jainil2004 I appreciate your PR. It's nicely done.

**Comment by Jainil2004** [comment]
@karsterr i am very joyful that you liked my work. please let me know if there are any issues and I'll be very happy to help

**Comment by karsterr** [comment]
> @karsterr i am very joyful that you liked my work. please let me know if there are any issues and I'll be very happy to help

Feel free to solve any issues if you want. You can check out other repositories too.
